version: '3'
services:
    elite-subsonic:
        container_name: 'elite-subsonic'
        image: 'ripsawuk/elite-subsonic:latest'
        env_file: 
           - .env
        restart: unless-stopped